### ISSUE TITLE
Failure in RabbitMQMessageConsumer causes job to be requeued.

### ISSUE THREAD

**Issue by calumbrodie** [SimpleBus/RabbitMQBundleBridge#20]
I'm using this bundle with SimpleBus and SimpleBus/AsynchronousBundle

https://github.com/SimpleBus/RabbitMQBundleBridge/blob/master/src/RabbitMQMessageConsumer.php
Consumer returns 'true' after processing a message, and false after an exception. However in the exception case this results in the message being requeued indefinitely.

https://github.com/videlalvaro/RabbitMqBundle/blob/master/RabbitMq/ConsumerInterface.php

The correct return value would be to use ConsumerInterface::MSG_ACK and ConsumerInterface::MSG_REJECT from the above.

https://www.rabbitmq.com/confirms.html

**Comment by calumbrodie** [comment]
Actually I see this behaviour was changed in the following PR:

https://github.com/SimpleBus/RabbitMQBundleBridge/pull/15

Why was this? The old behaviour looks correct to me.

**Comment by cmodijk** [comment]
@calumbrodie Yes, i think the old behaviour is correct en i thought @matthiasnoback already reverted this. The problem in #15 could be resolved using a Dead Letter Exchange we currently use such a implementation. I will create a pull request for the Documentation to explain this. I created a pull request with a revert #21

@matthiasnoback I was thinking we could also resolve the case for #15 by extending the `MessageConsumptionFailed` with the possibility to decide what to return. I created a pull request for this to #22

**Comment by calumbrodie** [comment]
@cmodijk Thanks for your work on this.

**Comment by matthiasnoback** [comment]
#21 has been merged, so this problem should now be fixed (just update your dependency to `~3.0`).

**Comment by cmodijk** [comment]
@matthiasnoback Tnx!
