### ISSUE TITLE
Extract core implementations into RabbitMQBridge

### ISSUE THREAD

**Issue by tPl0ch** [SimpleBus/RabbitMQBundleBridge#5]
Hey @matthiasnoback 

how about moving the core components into a Bridge as with the other bindings? I'd like to use this, but without symfony :)

**Comment by matthiasnoback** [comment]
I moved as much code as possible out of the bundle. The remaining code depends directly on Symfony, so it doesn't make sense to move it into a bridge or something. The only interesting thing would be to have a separate library which would use RabbitMQ without Symfony. Personally I think I'm not going to create such a library. If you or anyone else would like to do it, that would be very nice and they are welcome to do it within this GitHub organization.

**Comment by matthiasnoback** [comment]
This also means I'm closing the issue for now to clear the view on more urgent issues :)
